# yamllint disable rule:line-length
name: ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    runs-on: atlas
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - uses: https://github.com/cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://attic.candee.baby/canix https://cache.nixos.org
            trusted-public-keys = canix:uqr0nD3I0mfj9BYfZgTZHMaDKfI2yCTtSA5JGTWKUeg= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - name: nix flake check
        run: nix flake check --keep-going --print-build-logs
