{
  config,
  lib,
  options,
  ...
}: let
  cfg = config.canix-toolbelt.cloudHost;
  inherit (lib) optionalAttrs;
  nm = import ../../../lib/networkmanager.nix {inherit lib;};
  renderFamily = family: settings:
    {inherit (settings) method;}
    // lib.listToAttrs (lib.imap1 (index: address:
      lib.nameValuePair "address${toString index}" address)
    settings.addresses)
    // optionalAttrs (settings.dns != []) {dns = lib.concatStringsSep ";" settings.dns;}
    // optionalAttrs (settings.gateway != null) {
      route1 = "${
        if family == "ipv4"
        then "0.0.0.0/0"
        else "::/0"
      },${settings.gateway}";
    }
    // optionalAttrs settings.gatewayOnLink {route1_options = "onlink=true";};
  familyAssertions = family: let
    s = cfg.network.${family};
  in [
    {
      assertion = s.method != "manual" || (s.addresses != [] && s.gateway != null && s.dns != []);
      message = "cloudHost: manual ${family} requires addresses, a gateway and DNS servers.";
    }
    {
      assertion = s.method == "manual" || (s.addresses == [] && s.gateway == null && s.dns == [] && !s.gatewayOnLink);
      message = "cloudHost: ${family} static settings require method = manual.";
    }
  ];
in {
  config = lib.mkIf cfg.enable (lib.mkMerge ([
      {
        assertions =
          [
            {
              assertion = cfg.network.interfaceName != null || cfg.network.macAddress != null;
              message = "cloudHost: select the uplink by interfaceName, macAddress, or both.";
            }
            {
              assertion = cfg.network.ipv4.method != "disabled" || cfg.network.ipv6.method != "disabled";
              message = "cloudHost: enable at least one uplink address family.";
            }
            {
              assertion = cfg.network.ipv6.method == "disabled" || cfg.network.mtu >= 1280;
              message = "cloudHost: IPv6 requires an MTU of at least 1280.";
            }
            {
              assertion =
                config.networking.networkmanager.enable
                && !config.networking.useNetworkd
                && !config.systemd.network.enable
                && !config.networking.dhcpcd.enable;
              message = "cloudHost: NetworkManager must be the sole runtime network manager.";
            }
          ]
          ++ familyAssertions "ipv4" ++ familyAssertions "ipv6";
        networking = {
          useDHCP = false;
          dhcpcd.enable = false;
          networkmanager = {
            enable = true;
            # Avoid a competing autogenerated DHCP connection, particularly on a
            # statically routed guest. Explicit profiles remain allowed.
            settings.main.no-auto-default = "*";
            ensureProfiles.profiles.cloud-uplink = nm.mkEthernetProfile {
              id = "cloud-uplink";
              inherit (cfg.network) interfaceName;
              ethernet =
                {mtu = toString cfg.network.mtu;}
                // optionalAttrs (cfg.network.macAddress != null) {mac-address = cfg.network.macAddress;};
              ipv4 = renderFamily "ipv4" cfg.network.ipv4;
              ipv6 = renderFamily "ipv6" cfg.network.ipv6;
            };
          };
        };
        systemd.network.enable = false;
      }
    ]
    ++ lib.optionals (lib.hasAttrByPath ["facter" "detected" "dhcp" "interfaces"] options) [
      {
        facter.detected.dhcp.interfaces = [];
      }
    ]));
}
